/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campominado;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.Collections;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author igorthierrry
 */
public class CampoMinadoTela extends javax.swing.JFrame {

    static String[] valores = new String[4];
    static int vidas = 5;
    //static int nivelDoPainel = 1;
    private JPanel panelNivel1;
    private JPanel panelNivel2;
    private JPanel panelNivel3;
    private JPanel panelNivel4;

    /**
     * Creates new form CampoMinadoTela
     */
    public CampoMinadoTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVidas = new javax.swing.JTextField();
        pnCampo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Campo Minado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Vidas:");

        txtVidas.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVidas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnCampo.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        inicio();
    }//GEN-LAST:event_formWindowActivated

    public void inicio() {
        txtVidas.setText(Integer.toString(CampoMinadoTela.vidas));

        this.pnCampo.setLayout(new GridLayout(4, 1));

     

        valores[0] = "BOMBA";
        valores[1] = "SETA";
        valores[2] = "BOMBA";
        valores[3] = "INTERROGAÇÃO";

        panelNivel1 = gerarNivel();
        panelNivel1.setName("1");
        this.pnCampo.add(panelNivel1);
        bloquearNivel(panelNivel1);

        panelNivel2 = gerarNivel();
        panelNivel2.setName("2");
        this.pnCampo.add(panelNivel2);
        bloquearNivel(panelNivel2);

        panelNivel3 = gerarNivel();
        panelNivel3.setName("3");
        this.pnCampo.add(panelNivel3);
        bloquearNivel(panelNivel3);

        panelNivel4 = gerarNivel();
        panelNivel4.setName("4");
        this.pnCampo.add(panelNivel4);

        addAcaoBotao(panelNivel4);
        addAcaoBotao(panelNivel3);
        addAcaoBotao(panelNivel2);
        addAcaoBotao(panelNivel1);

    }

    public JPanel gerarNivel() {

        JPanel painel = new JPanel(new GridLayout());
        painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Random rdn = new Random();

        Collections.shuffle(Arrays.asList(valores));

        for (int i = 0; i < 4; i++) {

            BotaoJogo btn = new BotaoJogo();
            btn.setTipoBotao(valores[i]);
            btn.setSize(20, 10);
            //btn.setLocation(x += 15, y += 15);
            btn.setText("Click");
            btn.setMargin(new Insets(0, 10, 0, 20));

            //tela.getContentPane().add(btn);           
            painel.add(btn);
        }
        //painel.setName(Integer.toString(nivelDoPainel));
        //nivelDoPainel++;

        return painel;
    }

    public void bloquearNivel(JPanel pnNivel) {

        Component[] objetos = pnNivel.getComponents();

        for (Component obj : objetos) {
            BotaoJogo btn = (BotaoJogo) obj;
            btn.setEnabled(false);
        }

    }

    public void liberarNivel(JPanel pnNivel) {

        Component[] objetos = pnNivel.getComponents();

        for (Component obj : objetos) {
            ((BotaoJogo) obj).setEnabled(true);
        }
    }

    public void fimDeJogo() {

        Component[] paineis = pnCampo.getComponents();
        for (Component painel : paineis) {
            bloquearNivel((JPanel) painel);
        }
    }

//    public void restartJogo() {
//        
//        fimDeJogo();
//        
//        Component[] paineis = pnCampo.getComponents();
//
//        for (Component painel : paineis) {
//            JPanel painelAlvo = (JPanel) painel;
//            if ("4".equals(painelAlvo.getName())) {
//                liberarNivel(painelAlvo);
//            }
//        }
//
//    }
    public void addAcaoBotao(JPanel painelAlvo) {
        Component[] objetos = painelAlvo.getComponents();

        for (Component obj : objetos) {
            BotaoJogo btn = (BotaoJogo) obj;
            btn.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JOptionPane.showMessageDialog(null, btn.getTipoBotao());

                    switch (btn.getTipoBotao()) {
                        case "BOMBA":
                            CampoMinadoTela.vidas--;
                            if (CampoMinadoTela.vidas <= 0) {
                                fimDeJogo();
                                JOptionPane.showMessageDialog(null, "Game Over!!!");

//                                int resposta = JOptionPane.showConfirmDialog(null, "Deseja tentar novamente?", "Game Over!!!", JOptionPane.YES_NO_OPTION);
//                                if (resposta == JOptionPane.YES_OPTION) {
//                                    restartJogo();
//                                } else {
//                                    fimDeJogo();
//                                }
                            }
                            btn.setEnabled(false);
                            break;
                        case "SETA":
                            btn.setEnabled(false);
                            int nivelAtual = Integer.parseInt(painelAlvo.getName());

                            switch (nivelAtual) {
                                case 1:
                                    JOptionPane.showMessageDialog(null, "You Win!!!");
                                    break;
                                case 2:
                                    liberarNivel(getPanelNivel1());
                                    break;
                                case 3:
                                    liberarNivel(getPanelNivel2());
                                    break;
                                case 4:
                                    liberarNivel(getPanelNivel3());
                                    break;
                            }

                            break;
                        case "INTERROGAÇÃO":
                            btn.setEnabled(false);
                            CampoMinadoTela.vidas++;
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Opção: " + btn.getTipoBotao() + "Não é válida!");
                    }

                }
            });
        }
    }

    public JPanel getPanelNivel1() {
        return panelNivel1;
    }

    public JPanel getPanelNivel2() {
        return panelNivel2;
    }

    public JPanel getPanelNivel3() {
        return panelNivel3;
    }

    public JPanel getPanelNivel4() {
        return panelNivel4;
    }

    public JPanel getPnCampo() {
        return pnCampo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampoMinadoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnCampo;
    private javax.swing.JTextField txtVidas;
    // End of variables declaration//GEN-END:variables
}
